/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package handcricket;

/**
 *
 * @author MAHE
 */
public class Bowling extends javax.swing.JFrame {
int overn,userscore,balls,userbowll,comps,score1=0,i=0;
String userbal,compruns;
    /**
     * Creates new form Bowling
     */
    public Bowling() {
        initComponents();
    }
     public Bowling(int overn) {
        initComponents();
        this.overn=overn;
    }
     public Bowling(int userscore,int balls){
         initComponents();
         this.userscore=userscore;
         this.balls=balls;
         jLabel4.setText(Integer.toString(userscore));
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comprun = new javax.swing.JTextField();
        userball = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userbowl = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Computer is batting");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 39, 237, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("You are bowling");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 39, 193, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Enter numbers btw 1-6 to bowl");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 140, 218, 17);

        comprun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(comprun);
        comprun.setBounds(66, 86, 90, 40);

        userball.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(userball);
        userball.setBounds(377, 86, 100, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("0");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 200, 70, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("Your Score:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 200, 139, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Comp Score:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(137, 250, 152, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("0");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(309, 242, 100, 40);

        userbowl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        userbowl.setForeground(new java.awt.Color(0, 0, 153));
        userbowl.setText("Bowl");
        userbowl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbowlActionPerformed(evt);
            }
        });
        getContentPane().add(userbowl);
        userbowl.setBounds(161, 302, 308, 53);

        error.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        error.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(error);
        error.setBounds(205, 100, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 160, 500, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/handcricket/AACC.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 10, 600, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userbowlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbowlActionPerformed
         userbal=userball.getText();
         userbowll=Integer.parseInt(userbal);
       
        
         
    if (userbowll>0 && userbowll<=6)
        
    {
         comps=(int)(Math.random()*6+1);
         compruns=Integer.toString(comps);
         comprun.setText(compruns);
         score1=score1+comps;
         if(comps!=userbowll){
             jLabel7.setText(Integer.toString(score1));
             if(userscore!=0){
                 if(score1>userscore){
                    jLabel8.setText("Computer has won the match!!");
                 }
             }
         }
         
         else if(comps==userbowll){
             jLabel8.setText("Computer is out!");
             jLabel7.setText(Integer.toString(score1-comps));
             if(userscore!=0){
                 if(userscore>score1){
                    jLabel8.setText("You have won the match!!");
                 }else{
                     jLabel8.setText("Computer has won the match!!");
                 }
             }else if(userscore==0){
                for(int j=0;j<3000;j++);
                Batting batting=new Batting((score1-comps),balls);
                batting.setVisible(true);
             }
         }else if(i==balls){
             if (userscore==0)
             {
             jLabel4.setText("Your Innings is over! Time to change sides!");
             }
             else { jLabel4.setText("You have won the match");}
             for(int j=0;j<3000;j++);
             Batting batting=new Batting(score1,balls);
             batting.setVisible(true);
         }
        
         
         userball.setText("");
    }//GEN-LAST:event_userbowlActionPerformed
    else {error.setText("ERROR");   userball.setText(""); }
    i=i+1;
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bowling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bowling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField comprun;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField userball;
    private javax.swing.JButton userbowl;
    // End of variables declaration//GEN-END:variables
}
