/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package handcricket;

/**
 *
 * @author MAHE
 */
public class Play extends javax.swing.JFrame {
    String userin;
    String decision;
    int overnum;
    int ui;
    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fivebtn = new javax.swing.JRadioButton();
        tenbtn = new javax.swing.JRadioButton();
        twelvebtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userinput = new javax.swing.JTextField();
        toosbtn = new javax.swing.JButton();
        decisionbox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("Choose Number Of Overs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(83, 50, 176, 17);

        overgroup.add(fivebtn);
        fivebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fivebtn.setForeground(new java.awt.Color(255, 0, 0));
        fivebtn.setLabel("5 Overs");
        fivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebtnActionPerformed(evt);
            }
        });
        getContentPane().add(fivebtn);
        fivebtn.setBounds(70, 87, 69, 23);

        overgroup.add(tenbtn);
        tenbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tenbtn.setForeground(new java.awt.Color(255, 0, 51));
        tenbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tenbtn.setLabel("10 Overs");
        tenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenbtnActionPerformed(evt);
            }
        });
        getContentPane().add(tenbtn);
        tenbtn.setBounds(70, 122, 75, 23);

        overgroup.add(twelvebtn);
        twelvebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        twelvebtn.setForeground(new java.awt.Color(255, 0, 51));
        twelvebtn.setLabel("12 Overs");
        twelvebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelvebtnActionPerformed(evt);
            }
        });
        getContentPane().add(twelvebtn);
        twelvebtn.setBounds(70, 163, 75, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Choose ODD/EVEN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 50, 134, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Choose Number btw 1-6");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 210, 171, 17);

        userinput.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        userinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userinputActionPerformed(evt);
            }
        });
        getContentPane().add(userinput);
        userinput.setBounds(262, 240, 100, 40);

        toosbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        toosbtn.setForeground(new java.awt.Color(0, 51, 255));
        toosbtn.setLabel("Toss");
        toosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toosbtnActionPerformed(evt);
            }
        });
        getContentPane().add(toosbtn);
        toosbtn.setBounds(240, 280, 142, 37);

        decisionbox.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        decisionbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Odd", "Even" }));
        decisionbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decisionboxActionPerformed(evt);
            }
        });
        getContentPane().add(decisionbox);
        decisionbox.setBounds(420, 83, 86, 20);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(225, 229, 161, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/handcricket/TOSS.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 630, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fivebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebtnActionPerformed
       overnum=5; // TODO add your handling code here:
    }//GEN-LAST:event_fivebtnActionPerformed

    private void userinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userinputActionPerformed

    private void toosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toosbtnActionPerformed
       if(fivebtn.isSelected()){
           overnum=5;
       }else if(tenbtn.isSelected()){
           overnum=10;
       }else if(twelvebtn.isSelected()){
           overnum=12;
       }
        decision=(String)decisionbox.getSelectedItem();
        userin=userinput.getText();
        ui=Integer.parseInt(userin);
        if (ui>=1 && ui<=6)
        {
        Tossdecide td=new Tossdecide(decision,overnum,ui);
        td.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_toosbtnActionPerformed
        else{
            jLabel4.setText("Wrong input, please try again.");
                    }
                
    }
    private void tenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenbtnActionPerformed
        overnum=10;        // TODO add your handling code here:
    }//GEN-LAST:event_tenbtnActionPerformed

    private void twelvebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelvebtnActionPerformed
        overnum=12;        // TODO add your handling code here:
    }//GEN-LAST:event_twelvebtnActionPerformed

    private void decisionboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decisionboxActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_decisionboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox decisionbox;
    private javax.swing.JRadioButton fivebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.ButtonGroup overgroup;
    private javax.swing.JRadioButton tenbtn;
    private javax.swing.JButton toosbtn;
    private javax.swing.JRadioButton twelvebtn;
    private javax.swing.JTextField userinput;
    // End of variables declaration//GEN-END:variables
}
