/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package handcricket;

/**
 *
 * @author MAHE
 */
public class Tossdecide extends javax.swing.JFrame {
String desc;
int overno;
int u;
int comp;
int num;
int screen;
    /**
     * Creates new form Tossdecide
     */
    public Tossdecide() {
        initComponents();
    }
    public Tossdecide(String desc,int overno,int u){
        initComponents();
        this.desc=desc;
        this.overno=overno;
        this.u=u;
        jLabel3.setText(Integer.toString(u));
        comp=(int)(Math.random()*6+1);
        jLabel4.setText(Integer.toString(comp));
        num=u+comp;
        if((num%2==0) && desc.equalsIgnoreCase("Even")){
            jLabel6.setText("You have won the toss! You are batting!");
            screen=1;
             
        }else if((num%2!=0) && desc.equalsIgnoreCase("Odd")){
            jLabel6.setText("You have won the toss! You are batting!");
            screen=1;
             
        }else if((num%2==0)&&desc.equalsIgnoreCase("Odd")){
            jLabel6.setText("Oh you've lost the toss! You are bowling!");
            screen=2; 
            
        }else if((num%2!=0)&&desc.equalsIgnoreCase("Even")){
            jLabel6.setText("Oh you've lost the toss! You are bowling!");
            screen=2; 
            
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        batbtn = new javax.swing.JButton();
        bowlbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Your choice");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 220, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Computer's choice");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 120, 360, 44);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 170, 120, 70);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 160, 110, 60);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 380, 120, 60);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 350, 289, 40);

        batbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        batbtn.setForeground(new java.awt.Color(0, 0, 204));
        batbtn.setText("BAT");
        batbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batbtnActionPerformed(evt);
            }
        });
        getContentPane().add(batbtn);
        batbtn.setBounds(80, 260, 130, 70);

        bowlbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bowlbtn.setForeground(new java.awt.Color(51, 51, 255));
        bowlbtn.setText("BOWL");
        bowlbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowlbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bowlbtn);
        bowlbtn.setBounds(390, 270, 110, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/handcricket/TSD.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batbtnActionPerformed
       if(screen==1){
       bowlbtn.setEnabled(false);
       batbtn.setEnabled(true);
        Batting b=new Batting(overno);
        b.setVisible(true);
    }//GEN-LAST:event_batbtnActionPerformed
    }
    private void bowlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowlbtnActionPerformed
       if(screen==2){
           batbtn.setEnabled(false);
           bowlbtn.setEnabled(true);
           Bowling bo=new Bowling(overno);
           bo.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_bowlbtnActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tossdecide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tossdecide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tossdecide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tossdecide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tossdecide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batbtn;
    private javax.swing.JButton bowlbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
